# Alternative Docker Compose configuration using host directory for model persistence
# This version stores models in a local ./models_cache directory on your host machine
version: '3.8'

services:
  zonos:
    build:
      context: .
      dockerfile: Dockerfile    container_name: zonos_container
    runtime: nvidia
    ports:
      - "7860:7860"  # Gradio web interface
    stdin_open: true
    tty: true
    command: ["python3", "gradio_interface.py"]
    volumes:
      # Mount host directory for model cache persistence
      # This stores models in ./models_cache on your host machine
      - ./models_cache:/root/.cache/huggingface
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - GRADIO_SHARE=True
      - HF_HOME=/root/.cache/huggingface

# Usage:
# docker-compose -f docker-compose.host-volumes.yml up
