version: '3.8'

services:
  kokoro-init:
    image: busybox
    command: ["sh", "-c", "echo 'Initializing Kokoro TTS...' && sleep 2"]
    
  kokoro-tts-server:
    image: kprinssu/kokoro-fastapi:latest
    depends_on:
      - kokoro-init
    ports:
      - "8005:8880"  # Map external 8005 to internal 8880
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    volumes:
      - ./models:/app/models
      - ./audio_cache:/app/audio_cache
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    
networks:
  default:
    name: kokoro-network
    driver: bridge
